import { useEffect, useState } from 'react';
import { Alert, Pressable, StyleSheet, View } from 'react-native';
import { useRouter } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';

import { ThemedText } from '@/components/themed-text';
import { ThemedView } from '@/components/themed-view';
import { AppTextInput } from '@/src/components/app-text-input';
import { KeyboardAwareScrollView } from '@/src/components/keyboard-aware-scroll-view';
import { createPortfolioSnapshot, listAccountsByPortfolio, listAssets, listPortfolios, listPriceObservations, listTransactions } from '../data/wealth.repository';
import { parseNonNegativeDecimal } from '../model/decimal';
import { projectLedger } from '../services/ledger-projection';
import { valuePortfolio } from '../services/portfolio-valuation';

export default function NewSnapshotScreen() {
  const db = useSQLiteContext(); const router = useRouter();
  const [total, setTotal] = useState<string>(); const [baseCurrency, setBaseCurrency] = useState<string>(); const [portfolioId, setPortfolioId] = useState<string>(); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [reportedTotal, setReportedTotal] = useState(''); const [blockingMessage, setBlockingMessage] = useState<string>(); const [saving, setSaving] = useState(false);
  useEffect(() => { let active = true; void (async () => { try { const portfolio = (await listPortfolios(db))[0]; if (!portfolio) { if (active) setBlockingMessage('Create a portfolio transaction before recording a snapshot.'); return; } const [accounts, assets, transactions, prices] = await Promise.all([listAccountsByPortfolio(db, portfolio.id), listAssets(db), listTransactions(db), listPriceObservations(db)]); const projection = projectLedger({ portfolio, accounts, assets, transactions }); const valuation = valuePortfolio(portfolio, projection, assets, prices); const blockingIssues = [...projection.issues, ...valuation.issues].filter((item) => item.code === 'MISSING_PRICE' || item.severity === 'blocking'); const missingAssetNames = blockingIssues.flatMap((item) => item.assetId ? [assets.find((asset) => asset.id === item.assetId)?.name ?? 'an asset'] : []); if (active) { setPortfolioId(portfolio.id); setBaseCurrency(portfolio.baseCurrency); setTotal(valuation.totalValue); setBlockingMessage(blockingIssues.length ? `Update a usable ${portfolio.baseCurrency} price for ${[...new Set(missingAssetNames)].join(', ')} before recording a snapshot.` : undefined); } } catch { if (active) setBlockingMessage('Could not load the current valuation. Return to Wealth and check the recorded data.'); } })(); return () => { active = false; }; }, [db]);
  async function save() { if (!portfolioId || !total || !baseCurrency) return Alert.alert('Still loading', 'Wait for the current valuation to finish loading.'); if (blockingMessage) return Alert.alert('Snapshot incomplete', blockingMessage); try { setSaving(true); await createPortfolioSnapshot(db, { portfolioId: portfolioId as never, snapshotDate: date as never, totalValue: parseNonNegativeDecimal(total), baseCurrency: baseCurrency as never, source: 'MANUAL', ...(reportedTotal.trim() ? { reportedTotalValue: parseNonNegativeDecimal(reportedTotal) } : {}) }); router.replace('/wealth'); } catch { Alert.alert('Could not save snapshot', 'Use YYYY-MM-DD and a non-negative broker-reported total when provided.'); } finally { setSaving(false); } }
  return <ThemedView style={styles.container}><KeyboardAwareScrollView contentContainerStyle={styles.content}><ThemedText type="title">Record snapshot</ThemedText><ThemedText>A snapshot preserves today’s reconstructed total. Future price changes will not change it.</ThemedText><View style={styles.card}><ThemedText type="defaultSemiBold">Current reconstructed total: {total ?? 'Loading…'} {baseCurrency ?? ''}</ThemedText><ThemedText>{blockingMessage ?? 'All open holdings have a usable base-currency price.'}</ThemedText></View><Field label="Snapshot date (YYYY-MM-DD)" value={date} onChangeText={setDate} /><Field label="Broker-reported total (optional)" value={reportedTotal} onChangeText={setReportedTotal} keyboardType="decimal-pad" /><Pressable disabled={saving} onPress={() => void save()} style={[styles.save, saving && styles.disabled]}><ThemedText type="defaultSemiBold">{saving ? 'Saving...' : 'Save snapshot'}</ThemedText></Pressable></KeyboardAwareScrollView></ThemedView>;
}
function Field({ label, ...props }: { label: string; value: string; onChangeText: (value: string) => void; keyboardType?: 'decimal-pad' }) { return <View style={styles.field}><ThemedText type="defaultSemiBold">{label}</ThemedText><AppTextInput {...props} placeholder={label} /></View>; }
const styles = StyleSheet.create({ container: { flex: 1 }, content: { padding: 24, gap: 16 }, card: { borderWidth: 1, borderColor: '#ccc', borderRadius: 12, padding: 16, gap: 8 }, field: { gap: 8 }, save: { padding: 14, borderRadius: 12, alignItems: 'center', backgroundColor: '#e0e7ff' }, disabled: { opacity: 0.5 } });
