import { useFocusEffect } from '@react-navigation/native';
import { useRouter } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { ThemedText } from '@/components/themed-text';
import { ThemedView } from '@/components/themed-view';
import { listPortfolioSnapshots, listPortfolios, listTransactions } from '../data/wealth.repository';
import { buildPerformanceSummary, type PerformanceSummary } from '../services/performance';

const money = (value: string) => new Intl.NumberFormat('de-DE', { style: 'currency', currency: 'EUR' }).format(Number(value));
export default function PerformanceScreen() { const db = useSQLiteContext(); const router = useRouter(); const [summary, setSummary] = useState<PerformanceSummary>(); const [loading, setLoading] = useState(true); useFocusEffect(useCallback(() => { let active = true; void (async () => { setLoading(true); try { const portfolio = (await listPortfolios(db))[0]; if (!portfolio) return; const [transactions, snapshots] = await Promise.all([listTransactions(db), listPortfolioSnapshots(db, portfolio.id)]); if (active) setSummary(buildPerformanceSummary(portfolio, transactions, snapshots)); } finally { if (active) setLoading(false); } })(); return () => { active = false; }; }, [db])); return <ThemedView style={styles.container}>{loading ? <View style={styles.centered}><ActivityIndicator /></View> : <ScrollView contentContainerStyle={styles.content}><ThemedText type="title">Performance</ThemedText><ThemedText>Recorded snapshots are historical evidence; contributions are shown separately from investment gain.</ThemedText>{!summary || summary.points.length === 0 ? <View style={styles.card}><ThemedText>No history yet. Record at least one portfolio snapshot to start a performance history.</ThemedText><Pressable onPress={() => router.push('/wealth/snapshot')} style={styles.button}><ThemedText>Record snapshot</ThemedText></Pressable></View> : <><View style={styles.card}><ThemedText type="defaultSemiBold">Money-weighted return (annualized)</ThemedText><ThemedText>{summary.moneyWeightedReturn.annualRate ? `${Number(summary.moneyWeightedReturn.annualRate).toFixed(2)}%` : summary.moneyWeightedReturn.reason}</ThemedText><ThemedText>Time-weighted return: {summary.timeWeightedReturnReason}</ThemedText></View><View style={styles.section}><ThemedText type="subtitle">Value vs. net contributions</ThemedText>{summary.points.map((point) => <View key={point.date} style={styles.card}><ThemedText type="defaultSemiBold">{point.date}</ThemedText><ThemedText>Portfolio value: {money(point.portfolioValue)}</ThemedText><ThemedText>Net contributions: {money(point.cumulativeNetContributions)}</ThemedText><ThemedText>Simple gain: {money(point.simpleGain)}</ThemedText></View>)}</View></>}</ScrollView>}</ThemedView>; }
const styles = StyleSheet.create({ container: { flex: 1 }, centered: { flex: 1, justifyContent: 'center' }, content: { padding: 24, gap: 16 }, card: { borderWidth: 1, borderColor: '#ccc', borderRadius: 12, padding: 16, gap: 8 }, button: { borderWidth: 1, borderColor: '#ccc', borderRadius: 12, padding: 12, alignSelf: 'flex-start' }, section: { gap: 12 } });
