import { Stack, useLocalSearchParams, useRouter } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { ThemedText } from '@/components/themed-text';
import { ThemedView } from '@/components/themed-view';
import { getTransactionById, softDeleteTransaction } from '../data/wealth.repository';
import type { TransactionId, WealthTransaction } from '../model/wealth.types';

export default function TransactionDetailScreen() { const db = useSQLiteContext(); const router = useRouter(); const params = useLocalSearchParams<{ id?: string }>(); const id = params.id; const [item, setItem] = useState<WealthTransaction | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; void (async () => { if (!id) return; setLoading(true); const result = await getTransactionById(db, id as TransactionId); if (active) { setItem(result); setLoading(false); } })(); return () => { active = false; }; }, [db, id]);
  function remove() { if (!item) return; Alert.alert('Delete transaction?', 'This hides the transaction from normal views. It remains in the local audit history.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: async () => { await softDeleteTransaction(db, item.id); router.replace('/wealth'); } }]); }
  return <ThemedView style={styles.container}><Stack.Screen options={{ title: item?.type ?? 'Transaction' }} />{loading ? <View style={styles.centered}><ActivityIndicator /></View> : !item ? <View style={styles.centered}><ThemedText type="title">Transaction not found</ThemedText></View> : <ScrollView contentContainerStyle={styles.content}><ThemedText type="title">{item.type}</ThemedText><View style={styles.actions}><Pressable style={styles.button} onPress={() => router.push({ pathname: '/wealth/[id]/edit', params: { id: item.id } })}><ThemedText>Edit</ThemedText></Pressable><Pressable style={styles.button} onPress={remove}><ThemedText>Delete</ThemedText></Pressable></View><View style={styles.card}><ThemedText>Date: {item.tradeDate}</ThemedText><ThemedText>Currency: {item.currency}</ThemedText>{'amount' in item ? <ThemedText>Amount: {item.amount}</ThemedText> : item.type === 'BUY' || item.type === 'SELL' ? <><ThemedText>Quantity: {item.quantity}</ThemedText><ThemedText>Unit price: {item.unitPrice}</ThemedText><ThemedText>Fees: {item.fees}</ThemedText><ThemedText>Taxes: {item.taxes}</ThemedText></> : null}{item.note ? <ThemedText>Note: {item.note}</ThemedText> : null}</View></ScrollView>}</ThemedView>; }
const styles = StyleSheet.create({ container: { flex: 1 }, centered: { flex: 1, justifyContent: 'center', padding: 24 }, content: { padding: 24, gap: 16 }, actions: { flexDirection: 'row', gap: 12 }, button: { borderWidth: 1, borderColor: '#ccc', borderRadius: 10, padding: 12 }, card: { borderWidth: 1, borderColor: '#ccc', borderRadius: 12, padding: 16, gap: 10 } });
