import * as DocumentPicker from 'expo-document-picker';
import { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { useRouter } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';

import { ThemedText } from '@/components/themed-text';
import { ThemedView } from '@/components/themed-view';
import { AppTextInput } from '@/src/components/app-text-input';
import { commitCanonicalCsvImport, findPersonalPortfolio, listAccountsByPortfolio, listAssets, listTransactionsByPortfolio } from '../data/wealth.repository';
import { CANONICAL_TRANSACTION_CSV_HEADERS, CANONICAL_TRANSACTION_CSV_VERSION, canCommitCanonicalCsvImport, isCanonicalTransactionCsvFilename, parseCanonicalTransactionsCsv, toCanonicalCsvImportCommit, validateCanonicalCsvImport, type CsvImportExistingData, type CsvImportPreview, type StagedCsvTransaction } from '../services/workbook-import';

export default function WorkbookImportScreen() {
  const db = useSQLiteContext(); const router = useRouter(); const [preview, setPreview] = useState<CsvImportPreview>(); const [existing, setExisting] = useState<CsvImportExistingData>(); const [busy, setBusy] = useState(false);
  const restage = (next: CsvImportPreview, data = existing) => { if (data) setPreview(validateCanonicalCsvImport(next, data)); };
  async function select() { try { const result = await DocumentPicker.getDocumentAsync({ type: '*/*', copyToCacheDirectory: true }); if (result.canceled) return; const asset = result.assets[0]; if (!isCanonicalTransactionCsvFilename(asset.name)) { Alert.alert('Choose a CSV file', 'This importer accepts a .csv file using the finance-cockpit transaction format.'); return; } const [portfolio, assets] = await Promise.all([findPersonalPortfolio(db), listAssets(db)]); const [accounts, transactions] = portfolio ? await Promise.all([listAccountsByPortfolio(db, portfolio.id), listTransactionsByPortfolio(db, portfolio.id)]) : [[], []]; const data = { portfolio: portfolio ?? undefined, accounts, assets, transactions }; setExisting(data); restage(parseCanonicalTransactionsCsv(await (await fetch(asset.uri)).arrayBuffer()), data); } catch { Alert.alert('Could not read CSV', 'Choose a UTF-8 finance-cockpit transaction CSV. Nothing was imported.'); } }
  function update(row: number, field: keyof StagedCsvTransaction, value: string | boolean) { if (preview) restage({ ...preview, transactions: preview.transactions.map((item) => item.row === row ? { ...item, [field]: value } : item) }); }
  async function commit() { if (!preview || !existing) return; try { setBusy(true); const result = await commitCanonicalCsvImport(db, toCanonicalCsvImportCommit(preview, existing.portfolio?.baseCurrency ?? 'EUR')); Alert.alert('Import complete', `${result.transactionCount} transactions were atomically imported.`); router.replace('/wealth'); } catch { Alert.alert('Import was not committed', 'The atomic import failed, so no staged records were saved. Review the CSV and try again.'); } finally { setBusy(false); } }
  const blocking = preview?.issues.filter((issue) => issue.severity === 'blocking') ?? [];
  return <ThemedView style={styles.container}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><ThemedText type="title">Import transactions</ThemedText><ThemedText>Import the exact UTF-8 CSV contract: {CANONICAL_TRANSACTION_CSV_VERSION}. The app stages and validates it locally before one atomic commit.</ThemedText><View style={styles.card}><ThemedText type="defaultSemiBold">Required header</ThemedText><ThemedText selectable>{CANONICAL_TRANSACTION_CSV_HEADERS.join(',')}</ThemedText></View><Pressable onPress={() => void select()} style={styles.button}><ThemedText type="defaultSemiBold">Select transaction CSV</ThemedText></Pressable>{preview ? <><View style={styles.card}><ThemedText type="defaultSemiBold">Staged: {preview.transactions.filter((item) => item.included).length} transactions</ThemedText><ThemedText>{blocking.length ? `${blocking.length} blocking issue(s) must be corrected or excluded.` : 'Ready for reviewed atomic import.'}</ThemedText></View><Pressable disabled={!canCommitCanonicalCsvImport(preview) || busy} onPress={() => void commit()} style={[styles.commit, (!canCommitCanonicalCsvImport(preview) || busy) && styles.disabled]}><ThemedText type="defaultSemiBold">{busy ? 'Importing…' : 'Confirm atomic import'}</ThemedText></Pressable>{preview.issues.map((issue, index) => <View key={`${issue.code}-${issue.row}-${index}`} style={[styles.issue, issue.severity === 'blocking' && styles.blocking]}><ThemedText type="defaultSemiBold">{issue.severity === 'blocking' ? 'Blocked' : 'Review'}{issue.row ? ` · row ${issue.row}` : ''}</ThemedText><ThemedText>{issue.message}</ThemedText></View>)}{preview.transactions.map((row) => <TransactionCard key={row.row} row={row} issues={preview.issues.filter((issue) => issue.row === row.row)} onChange={update} />)}</> : null}</ScrollView></ThemedView>;
}
function TransactionCard({ row, issues, onChange }: { row: StagedCsvTransaction; issues: CsvImportPreview['issues']; onChange: (row: number, field: keyof StagedCsvTransaction, value: string | boolean) => void }) { return <View style={[styles.card, !row.included && styles.excluded]}><View style={styles.row}><ThemedText type="defaultSemiBold">Row {row.row}</ThemedText><Pressable onPress={() => onChange(row.row, 'included', !row.included)} style={styles.smallButton}><ThemedText>{row.included ? 'Exclude' : 'Include'}</ThemedText></Pressable></View>{row.included ? <><Edit label="Sequence" value={row.sequence} onChangeText={(value) => onChange(row.row, 'sequence', value)} /><Edit label="Type" value={row.type} onChangeText={(value) => onChange(row.row, 'type', value.toUpperCase())} /><Edit label="Trade date" value={row.date} onChangeText={(value) => onChange(row.row, 'date', value)} /><Edit label="Account" value={row.account} onChangeText={(value) => onChange(row.row, 'account', value)} /><Edit label="ISIN" value={row.isin} onChangeText={(value) => onChange(row.row, 'isin', value.toUpperCase())} /><Edit label="Ticker" value={row.ticker} onChangeText={(value) => onChange(row.row, 'ticker', value.toUpperCase())} /><Edit label="Asset name" value={row.assetName} onChangeText={(value) => onChange(row.row, 'assetName', value)} />{row.type === 'CONTRIBUTION' || row.type === 'WITHDRAWAL' ? <Edit label="Amount" value={row.amount} onChangeText={(value) => onChange(row.row, 'amount', value)} /> : <><Edit label="Quantity" value={row.quantity} onChangeText={(value) => onChange(row.row, 'quantity', value)} /><Edit label="Unit price" value={row.unitPrice} onChangeText={(value) => onChange(row.row, 'unitPrice', value)} /><Edit label="Fees" value={row.fees} onChangeText={(value) => onChange(row.row, 'fees', value)} /><Edit label="Taxes" value={row.taxes} onChangeText={(value) => onChange(row.row, 'taxes', value)} /></>}<Edit label="Currency" value={row.currency} onChangeText={(value) => onChange(row.row, 'currency', value.toUpperCase())} /><Edit label="FX rate to base (if needed)" value={row.fxRateToBase} onChangeText={(value) => onChange(row.row, 'fxRateToBase', value)} />{issues.map((issue, index) => <ThemedText key={index}>{issue.severity === 'blocking' ? 'Blocked: ' : 'Review: '}{issue.message}</ThemedText>)}</> : <ThemedText>Excluded rows are not validated or imported.</ThemedText>}</View>; }
function Edit({ label, value, onChangeText }: { label: string; value: string; onChangeText: (value: string) => void }) { return <View style={styles.field}><ThemedText>{label}</ThemedText><AppTextInput value={value} onChangeText={onChangeText} /></View>; }
const styles = StyleSheet.create({ container: { flex: 1 }, content: { padding: 24, gap: 14 }, button: { borderWidth: 1, borderColor: '#ccc', borderRadius: 12, padding: 14, alignItems: 'center' }, commit: { borderRadius: 12, padding: 14, alignItems: 'center', backgroundColor: '#e0e7ff' }, disabled: { opacity: 0.5 }, card: { borderWidth: 1, borderColor: '#ccc', borderRadius: 12, padding: 12, gap: 8 }, issue: { borderWidth: 1, borderColor: '#d6b76a', borderRadius: 12, padding: 12, gap: 4 }, blocking: { borderColor: '#c95050' }, excluded: { opacity: 0.55 }, row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, smallButton: { borderWidth: 1, borderColor: '#ccc', borderRadius: 8, padding: 7 }, field: { gap: 3 } });
