import assert from 'node:assert/strict';
import test from 'node:test';
import { parseNonNegativeDecimal } from '../model/decimal';
import type { Account, Asset, Portfolio, WealthTransaction } from '../model/wealth.types';
import { projectLedger } from './ledger-projection';

const portfolio = { id: 'portfolio-1', name: 'Fictional', baseCurrency: 'EUR' } as Portfolio;
const account = { id: 'account-1', portfolioId: portfolio.id, name: 'Broker A', baseCurrency: 'EUR', isActive: true } as Account;
const asset = { id: 'asset-1', name: 'Fictional ETF', assetType: 'ETF', bucket: 'CORE', strategyCategory: 'BROAD_MARKET', tradingCurrency: 'EUR', isActive: true } as Asset;
const cash = (type: 'CONTRIBUTION' | 'WITHDRAWAL', amount: string, date: string) => ({ id: `${type}-${date}`, type, accountId: account.id, tradeDate: date, sequence: 0, amount: parseNonNegativeDecimal(amount), currency: 'EUR', source: 'MANUAL' } as WealthTransaction);
const trade = (type: 'BUY' | 'SELL', quantity: string, price: string, fees: string, taxes: string, date: string) => ({ id: `${type}-${date}`, type, accountId: account.id, assetId: asset.id, tradeDate: date, sequence: 0, quantity: parseNonNegativeDecimal(quantity), unitPrice: parseNonNegativeDecimal(price), fees: parseNonNegativeDecimal(fees), taxes: parseNonNegativeDecimal(taxes), currency: 'EUR', source: 'MANUAL' } as WealthTransaction);
test('projects contribution, moving-average partial sale, cash, and realized results', () => { const projection = projectLedger({ portfolio, accounts: [account], assets: [asset], transactions: [cash('CONTRIBUTION', '1000', '2026-01-01'), trade('BUY', '10', '100', '10', '0', '2026-01-02'), trade('BUY', '5', '120', '5', '0', '2026-01-03'), trade('SELL', '6', '150', '6', '9', '2026-01-04')] }); const position = projection.positions[0]; assert.equal(position.quantity, '9'); assert.equal(position.remainingCostBasis, '969'); assert.equal(position.realizedNetResult, '239'); assert.equal(projection.accountCash[0].cashBalance, '270'); assert.equal(projection.netExternalContributions, '1000'); });
test('retains lifetime realized results through full exit and re-entry', () => { const projection = projectLedger({ portfolio, accounts: [account], assets: [asset], transactions: [trade('BUY', '8', '100', '0', '0', '2026-01-01'), trade('SELL', '8', '125', '8', '0', '2026-01-02'), trade('BUY', '3', '90', '3', '0', '2026-01-03')] }); const position = projection.positions[0]; assert.equal(position.quantity, '3'); assert.equal(position.remainingCostBasis, '273'); assert.equal(position.realizedNetResult, '192'); });
test('reports oversells and negative cash without producing a negative position', () => { const projection = projectLedger({ portfolio, accounts: [account], assets: [asset], transactions: [trade('BUY', '5', '100', '0', '0', '2026-01-01'), trade('SELL', '6', '100', '0', '0', '2026-01-02')] }); assert.equal(projection.positions[0].quantity, '5'); assert.deepEqual(projection.issues.map((item) => item.code).sort(), ['NEGATIVE_CASH_BALANCE', 'OVERSELL']); });
test('uses accepted historical FX conversion for cost and cash', () => { const usdBuy = { ...trade('BUY', '2', '100', '2', '0', '2026-01-01'), currency: 'USD', fxRateToBase: parseNonNegativeDecimal('0.9') } as WealthTransaction; const projection = projectLedger({ portfolio, accounts: [account], assets: [asset], transactions: [usdBuy] }); assert.equal(projection.positions[0].remainingCostBasis, '181.8'); assert.equal(projection.accountCash[0].cashBalance, '-181.8'); });
