import { decimal, toDecimalString, type DecimalString } from '../model/decimal';
import type { Asset, Portfolio, PriceObservation, WealthIssue } from '../model/wealth.types';
import type { AggregatedPositionProjection, PortfolioProjection } from './ledger-projection';

export type ValuedHolding = AggregatedPositionProjection & { asset: Asset; marketValue?: DecimalString; unrealizedResult?: DecimalString; price?: PriceObservation };
export type AllocationSlice = { bucket: Asset['bucket'] | 'CASH'; value: DecimalString; percentage: DecimalString };
export type PortfolioValuation = { holdings: ValuedHolding[]; totalValue: DecimalString; investedValue: DecimalString; cashValue: DecimalString; totalCostBasis: DecimalString; totalUnrealizedResult: DecimalString; allocation: AllocationSlice[]; issues: WealthIssue[] };

function latestPrices(prices: PriceObservation[]) { const result = new Map<string, PriceObservation>(); for (const price of [...prices].sort((a, b) => b.observedAt.localeCompare(a.observedAt) || b.id.localeCompare(a.id))) if (!result.has(price.assetId)) result.set(price.assetId, price); return result; }
export function valuePortfolio(portfolio: Portfolio, projection: PortfolioProjection, assets: Asset[], prices: PriceObservation[], asOf = new Date().toISOString().slice(0, 10)): PortfolioValuation {
  const assetsById = new Map(assets.map((asset) => [asset.id, asset])); const priceByAssetId = latestPrices(prices); const issues: WealthIssue[] = []; let investedValue = decimal('0' as DecimalString); let totalCost = decimal('0' as DecimalString); let totalUnrealized = decimal('0' as DecimalString); const bucketValues = new Map<Asset['bucket'] | 'CASH', ReturnType<typeof decimal>>();
  const holdings = projection.aggregatedPositions.filter((position) => !position.isClosed).flatMap((position) => { const asset = assetsById.get(position.assetId); if (!asset) return []; const price = priceByAssetId.get(position.assetId); totalCost = totalCost.plus(position.remainingCostBasis); if (!price || price.currency !== portfolio.baseCurrency) { issues.push({ code: 'MISSING_PRICE', severity: 'warning', assetId: position.assetId, details: { reason: price ? 'price_not_in_base_currency' : 'no_price' } }); return [{ ...position, asset, ...(price ? { price } : {}) }]; } if (Math.floor((Date.parse(`${asOf}T00:00:00Z`) - Date.parse(`${price.observedAt}T00:00:00Z`)) / 86_400_000) > 7) issues.push({ code: 'STALE_PRICE', severity: 'warning', assetId: position.assetId, details: { observedAt: price.observedAt } }); const marketValue = decimal(position.quantity).times(price.price); const unrealizedResult = marketValue.minus(position.remainingCostBasis); investedValue = investedValue.plus(marketValue); bucketValues.set(asset.bucket, (bucketValues.get(asset.bucket) ?? decimal('0' as DecimalString)).plus(marketValue)); totalUnrealized = totalUnrealized.plus(unrealizedResult); return [{ ...position, asset, marketValue: toDecimalString(marketValue), unrealizedResult: toDecimalString(unrealizedResult), price }]; });
  const cashValue = projection.accountCash.reduce((sum, item) => sum.plus(item.cashBalance), decimal('0' as DecimalString)); if (!cashValue.isZero()) bucketValues.set('CASH', cashValue); const totalValue = investedValue.plus(cashValue); const allocation = [...bucketValues.entries()].map(([bucket, value]) => ({ bucket, value: toDecimalString(value), percentage: toDecimalString(totalValue.isZero() ? decimal('0' as DecimalString) : value.dividedBy(totalValue).times(100)) }));
  return { holdings, totalValue: toDecimalString(totalValue), investedValue: toDecimalString(investedValue), cashValue: toDecimalString(cashValue), totalCostBasis: toDecimalString(totalCost), totalUnrealizedResult: toDecimalString(totalUnrealized), allocation, issues };
}
